FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DEFAULT_TIMEOUT=120

WORKDIR /mlflow

RUN python -m pip install --upgrade pip --retries 5 --timeout 120 && \
    python -m pip install "mlflow==3.15.1" --retries 5 --timeout 120

EXPOSE 5000